{
 "title": "Calls",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Endpoints Status",
   "type": "gauge",
   "description": "Status of the monitored endpoints",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(health_status or up) ", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Number of Calls  Rate per second",
   "type": "timeseries",
   "description": "Number of Calls rate",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(calls_number{job=\"apps\"}[1m])"
    }
   ]
  },
  {
   "title": "Calls Duration Rate (5m)",
   "type": "timeseries",
   "description": "Number of Calls rate",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "rate(calls_duration[5m])" }
   ]
  }
 ]
}