global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

  external_labels:
      monitor: 'test'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
   - "alert.yml"


scrape_configs:

  #  - job_name: 'kafka'
  #  static_configs:
  #   - targets: 
  #     - kafka_broker:49999

  #- job_name: 'zookeeper'
  #   # metrics_path defaults to '/metrics'
  #   # scheme defaults to 'http'.
  #  static_configs:
  #   - targets: 
  #     - zookeeper:39999

  - job_name: 'apps'
    static_configs:
      - targets: 
        - faust_consumer:6066
        - faust_producer:6066
        - quart_producer:5000
        - quart_confluent_producer:5000

